
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 6

[font.bold]
family = "Meslo LGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Meslo LGM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Meslo LGM Nerd Font"
style = "Italic"

[font.normal]
family = "Meslo LGM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.95

[window.class]
general = "Alacritty"
instance = "Alacritty"

[cursor]
unfocused_hollow = true
blink_interval = 500
thickness = 0.15

[cursor.style]
shape = "Beam"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
# blinking = "Always"

# [window.padding]
# x = 10
# y = 10
