-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
vim.opt.winbar = "%=%m %f"

-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- capabilities = require("cmp_nvim_lsp").default_capabilities(capabilities)
--
-- local servers = {
--   tsserver = {
--     on_attach = on_attach,
--     capabilities = capabilities,
--     init_options = {
--       disableForScriptFiles = false, -- Set to false to enable for JavaScript files
--     },
--   },
-- }
--
-- local lspconfig = require("lspconfig")
-- for server, config in pairs(servers) do
--   lspconfig[server].setup(config)
-- end
