return {
  -- "neovim/nvim-lspconfig",
  -- opts = {
  --   servers = {
  --     biome = {
  --       cmd = { "biome", "lsp-proxy" },
  --       filetypes = {
  --         "astro",
  --         "css",
  --         "graphql",
  --         "javascript",
  --         "javascriptreact",
  --         "json",
  --         "jsonc",
  --         "svelte",
  --         "typescript",
  --         "typescript.tsx",
  --         "typescriptreact",
  --         "vue",
  --       },
  --       root_dir = require("lspconfig.util").root_pattern("biome.json", "biome.jsonc"),
  --       single_file_support = false,
  --     },
  --   },
  -- },
}

-- return {
--   "neovim/nvim-lspconfig",
--   opts = {
--     servers = {},
--   },
-- }
--
